schema_version = "1.0.0"
id = "LinkageObjectAligner"
version = "1.0.0"
name = "Linkage Object Aligner"
maintainer = "Linkage Design <acheck@linkage-d.com>"
tagline = "Demonstrates setting a custom oriented top view"
type = "add-on"
blender_version_min = "4.2.0"
# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]